# Generated by Django 3.2.3 on 2022-05-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
        ('servicios', '0002_auto_20210209_1921'),
    ]

    operations = [
    ]
